# Generated by Django 5.1.1 on 2024-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_address_usuario_ativo_usuario_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='preferencia_notificacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notification_preference',
            field=models.CharField(choices=[('E', 'Email'), ('S', 'SMS'), ('N', 'None')], default='E', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
